# Generated by Django 4.2.18 on 2025-01-28 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branchname', models.TextField()),
                ('branchlocation', models.TextField()),
                ('allowedemps', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empname', models.TextField()),
                ('empaddr', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.TextField()),
                ('worksat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='avapp.branch')),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cstname', models.TextField()),
                ('custaddress', models.TextField()),
                ('firsttime', models.BooleanField(default=True)),
                ('clientof', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='avapp.branch')),
            ],
        ),
    ]
