# Generated by Django 4.2.18 on 2025-01-29 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='employeeinSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='employeeoutSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
